// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Volvo.Trucks.App.Models;

namespace Volvo.Trucks.App.Migrations
{
    [DbContext(typeof(VolvoTrucksContext))]
    [Migration("20190128004816_Truck")]
    partial class Truck
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Volvo.Trucks.App.Models.Truck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int>("TruckModelID");

                    b.Property<string>("Version");

                    b.Property<DateTime>("Year");

                    b.HasKey("Id");

                    b.ToTable("Truck");
                });

            modelBuilder.Entity("Volvo.Trucks.App.Models.TruckModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int?>("TruckId");

                    b.HasKey("Id");

                    b.HasIndex("TruckId");

                    b.ToTable("TruckModel");
                });

            modelBuilder.Entity("Volvo.Trucks.App.Models.TruckModel", b =>
                {
                    b.HasOne("Volvo.Trucks.App.Models.Truck")
                        .WithMany("TruckModelCollection")
                        .HasForeignKey("TruckId");
                });
#pragma warning restore 612, 618
        }
    }
}
